# Generated by Django 5.0.7 on 2024-07-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_customers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customers",
            new_name="Customer",
        ),
    ]
